config:
  item-sell:
    compare-meta: true         # <- Compare display name, lore and customModelData
    compare-damage: false      # <- Compare item durability (damage)
    compare-model: true        # <- Compare customModelData
    compare-all: true          # <- Use isSimilar() to compare NBT and all other data

  economy:
    # Defines the default currency symbol for the main economy (VAULT)
    default-symbol: "$"

    # Currency symbol position
    # true = symbol appears before the value ($100)
    # false = symbol appears after the value (100$)
    symbol-before: true

    # Custom symbols for different server economies
    symbols:
      vault: "$"      # Main server currency
      tokens: "✦"     # Special tokens for events or rewards
      gems: "💎"       # Gems for premium purchases
      crystals: "✧"   # Crystals for special upgrades
      points: "Pts"   # Points for rank or achievement systems

  gui:
    # Button settings to interact with the shop
    buttons:
      # Mouse buttons used to buy and sell in the GUI
      # Available options: LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, MIDDLE
      buy: "LEFT"     # Button to buy items
      sell: "RIGHT"   # Button to sell items

    # Purchase/sell confirmation
    # Should a confirmation menu open before completing a transaction?
    purchase-confirmation:
      enabled: true   # true = require confirmation, false = instant transaction

    # Handling long titles in the GUI
    truncate-titles: true       # Shorten titles exceeding max length?
    max-title-length: 36        # Max title length before shortening with (...)

  command:

    admin:
      # Enable the admin command
      # Requires server restart to apply changes
      enabled: true
      # Base command name for admins
      name: adminshop
      # Alternate command aliases that work the same
      aliases:
        - jashop

    # Command to open the main shop menu
    shop:
      # Command activation (requires server restart)
      enabled: true
      # Permission control
      need-permissions: true             # Is a specific permission required to use this command?
      permission: shopmaster.open        # Permission required if need-permissions is true
      # Command settings
      name: sshop                         # Command name
      aliases: []                        # Alternate commands (empty list = no aliases)

      # Restrictions for the shop command
      black-list:
        # Worlds where the shop command is disabled
        world:
          - ExampleWorld                 # Example (replace with actual world names)
        # Game modes where the shop command is disabled
        gameModes:
          - ADVENTURE
          - CREATIVE
          - SPECTATOR

    # Command to quickly sell items
    sell:
      # Enable the sell system
      enabled: true                      # false = fully disables the /sell command
      # Permission control
      need-permissions: true             # Is permission required to use this command?
      permission: shopmaster.sell        # Permission required if need-permissions is true
      # Command settings
      name: ssell                         # Command name
      aliases: []                        # Alternate commands (empty list = no aliases)

      messages:
        # Transaction logging in server console
        log:
          enabled: true
          # Variables: {player}, {action} (bought/sold), {amount}, {item}, {money}, {shopName}
          message: "{player} {action} {amount} x {item} for {money} from {shopName} shop"

        # Message for simple sell (/sell hand)
        # Variables: {amount}, {item}, {earnings}
        simple: "&aYou sold &e{amount} x {item} &afor a total of &e${earnings}"

        # Detailed message config for multiple item sales
        summary:
          enabled: true
          show-itemized: true
          summary-text: "(summary)"
          format-items: "{amount}x {item} <gray>for <green>{earnings} <gray>(<aqua>{percent}%<gray>)"
          hover-lines:
            - "<yellow>Sale Summary:"
            - ""
            - "{format-items}"
            - ""
            - "<gray>Thanks for selling!"
          message: "<green>You sold <yellow>{total} <green>items for a total of <yellow>${earnings} {summary}"

      # Restrictions for the sell command
      black-list:
        world:
          - ExampleWorld
        gameModes:
          - ADVENTURE
          - CREATIVE
          - SPECTATOR

      # Subcommands of the sell command
      subcommands:
        # /sell all - Sells all sellable items from the inventory
        all:
          enabled: true
          need-permissions: true
          permission: shopmaster.sell.all

        # /sell hand - Sells the item in the player's hand
        hand:
          enabled: true
          need-permissions: true
          permission: shopmaster.sell.hand

        # /sell gui - Opens a GUI to add items; once closed, all items inside are sold
        gui:
          enabled: true
          show-itemized: true
          need-permissions: true
          permission: "shopmaster.sell.gui"
          default: true

  # Number and price format settings
  number-format:
    decimal-separator: "."
    grouping-separator: ","

    minimum-integer-digits: 1
    maximum-integer-digits: 32

    minimum-fraction-digits: 0
    maximum-fraction-digits: 8

    hide-fraction: true

    short-scale:
      enable-numbering: false
      limit: 1000000
      hand-decimal-limit: 2
      hand-number-limit: 32

      suffixes:
        - ""
        - "K"
        - "M"
        - "B"
        - "T"
        - "Q"

# Configuration file version (Do not modify)
file-version: 1
