name: ShopMaster
version: '${project.version}'
main: xshyo.us.shopMaster.ShopMaster
author: xShyo_
website: docs.xshyo.us
softdepend:
  - TokenManager
  - PlayerPoints
  - Vault
  - BreweryX
  - PlaceholderAPI
  - ExecutableItems
  - ExecutableBlocks
  - SCore
  - MMOItems
api-version: '1.16'